menu:
    Blog: /Inside-LINZ/
    Archive: /Inside-LINZ/archives/
    GitHub: https://github.com/codeforaotearoa
    Twitter: https://twitter.com/codeforaotearoa
    Email: mailto:info@codeforaotearoa.org
    Rss: /Inside-LINZ/atom.xml

favicon: /Inside-LINZ/favicon.png
logo: /Inside-LINZ/favicon.png

# Comment
# e.g disqus: seansun
disqus: insidelinz
duoshuo:

# Analytics
# google-analytics:
ga: UA-84242199-1

# Copyright Infomation
startyear: 2016
