menu:
    Blog: /
    Archive: /Inside-LINZ/archives/
    GitHub: https://github.com/codeforaotearoa
    Rss: /Inside-LINZ/atom.xml

favicon: /Inside-LINZ/favicon.png
logo: /Inside-LINZ/favicon.png

# Comment
# e.g disqus: seansun
disqus:
duoshuo:

# Analytics
# google-analytics:
ga: UA-84242199-1

# Copyright Infomation
startyear: 2016
